### ISSUE TITLE
Does it need a proxy？

### ISSUE THREAD

**Issue by horanf** [antfu/raycast-multi-translate#8]
I have configured global proxy, but it seems not work.

**Comment by tmkx** [comment]
Node.js will send requests directly by default.

solution 1: https://www.google.com/search?q=clash+enhanced+mode

solution 2:

```shell
pnpm add undici
```

src/translate.tsx
```diff
+import { ProxyAgent, setGlobalDispatcher } from 'undici'
 import { Main } from './components/Main'
 
+const agent = new ProxyAgent({
+  uri: 'http://127.0.0.1:7890',
+})
+
+setGlobalDispatcher(agent)
+
 export default Main
```

**Comment by horaoen** [comment]
> 

Thanks a lot, My clash version dose not support the solution 1. For solution 2, I think the plugin should dynamically adjust the proxy of the plugin by reading the terminal environment variable $http_proxy 、 $https_proxy 、 $all_proxy

**Comment by horaoen** [comment]
> Node.js will send requests directly by default.
> 
> solution 1: https://www.google.com/search?q=clash+enhanced+mode
> 
> solution 2:
> 
> ```shell
> pnpm add undici
> ```
> 
> src/translate.tsx
> 
> ```diff
> +import { ProxyAgent, setGlobalDispatcher } from 'undici'
>  import { Main } from './components/Main'
>  
> +const agent = new ProxyAgent({
> +  uri: 'http://127.0.0.1:7890',
> +})
> +
> +setGlobalDispatcher(agent)
> +
>  export default Main
> ```

Thanks a lot, for solution 1, my clash's version does not support, for solution 2, I think this is an elegant solution by dynamically reading the proxy environment variables($http_proxy, $https_proxy, $all_proxy) of the terminal to adjust above code.

**Comment by tmkx** [comment]
browsers will follow the system's proxy config, but terminals and other apps may not. for example, you need to declare env vars in shell config files like `.bashrc` to work for a terminal session, it will not exist unless you define it, so that we can't read `http_proxy` in raycast extension. in app, you can get system global proxy config by `scutil --proxy`.

by the way, the solution 2 is a temporary workaround for `@iamtraction/google-translate` which is using `undici` as its request library.

**Comment by horaoen** [comment]
> browsers will follow the system's proxy config, but terminals and other apps may not. for example, you need to declare env vars in shell config files like `.bashrc` to work for a terminal session, it will not exist unless you define it, so that we can't read `http_proxy` in raycast extension. in app, you can get system global proxy config by `scutil --proxy`.
> 
> by the way, the solution 2 is a temporary workaround for `@iamtraction/google-translate` which is using `undici` as its request library.
ok, i'll think about how to do it. I have defined `setpxy`  in `.zshrc`
<img width="1182" alt="image" src="https://github.com/antfu/raycast-multi-translate/assets/92006580/17f75e83-f8b4-46b4-b663-3086d330405f">

**Comment by hechunfeng123** [comment]
你才是真正的英雄
